---
# Apply common configuration to all hosts
- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
    - setup: # aka gather_facts
  roles:
  - common

# Configure and deploy ddclient servers.
- import_playbook: ddclients.yml


